eureka:
   client:
      service-url:
         defaultZone: http://eureka:eureka@127.0.0.1:8760/eureka/
   instance:
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}:@project.version@
spring:
   cloud:
      ## https://cloud.spring.io/spring-cloud-gateway/2.1.x/single/spring-cloud-gateway.html
      gateway:
         globalcors:
            corsConfigurations:
               '[/**]':
                  allowed-origins: '*'
                  allowed-methods: '*'
                  allowed-headers: '*'
                  allow-credentials: true
         routes:
         -  id: user-center-route
            uri: lb://user-center
            predicates:
            - Path=/user-center/**
            filters:
            - RewritePath=/user-center/(?<segment>.*), /$\{segment}
         -  id: file-server-route
            uri: lb://file-server
            predicates:
            - Path=/file-server/**
            filters:
            - StripPrefix=1