eureka:
   client:
      serviceUrl:
         defaultZone: http://eureka:eureka@springcloud-eureka-server:8760/eureka/ # springcloud-eureka-server 为 docker 容器名称
   instance:
      prefer-ip-Address: true
      instance-id: ${spring.application.name}:${server.port}:@project.version@
spring:
   datasource:
      url: jdbc:mysql://192.168.99.1:3306/pomelo-user?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource # http://localhost:8100/druid/index.html
      druid:
         stat-view-servlet:
            login-username: admin
            login-password: admin
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            temp:
               use_jdbc_metadata_defaults: false
            dialect: org.hibernate.dialect.MySQL5Dialect
            format_sql: true
cors:
   exposed-headers: Autherication
   allowed-origins: http://192.168.99.101
file-server:
   host: http://192.168.99.101:8200/
   user-avatar-url: http://192.168.99.101:8200/file/user/avatar/