server:
   port: 8760
eureka:
   instance:
      prefer-ip-address: false
      hostname: 127.0.0.1 # C:\Windows\System32\drivers\etc\hosts(Windows) | /etc/hosts(Linux)
   client:
      service-url:
         defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
      register-with-eureka: false
      fetch-registry: false
   server:
      eviction-interval-timer-in-ms: 30000
spring:
   security:
      basic:
         enabled: false
      user:
         name: eureka
         password: eureka