server:
   port: 8001
spring:
   profiles:
      active: test
   application:
      name: config-server
   cloud:
      config:
         server:
            git:
               uri: https://github.com/PomeloMan/SpringCloud
               default-label: master
               username: 
               password: 
               clone-on-start: true
               search-paths: '{application}'
               base-dir: D:\tmp