server:
   port: 8001
spring:
   profiles:
      active: test
   application:
      name: config-server
   cloud:
      config:
         server:
            native:
               search-locations: classpath:/config/{application}
            git:
               uri: https://github.com/PomeloMan/SpringCloud
               default-label: master
               username: null
               password: null
               clone-on-start: true
               search-paths: /config-server/'{application}'
               base-dir: D:\tmp